#pragma once

#define IDC_FILEPATH_EDIT 101
#define IDC_BROWSE_BUTTON 102
#define IDC_SIGN_BUTTON   103
#define IDC_SIGNATURE_BOX 104
#define IDC_PRIVATE_KEY   105
#define IDC_PARAM_SET     106
#define IDC_HASH_COMBO    107
#define IDC_STATUS_TEXT   108
#define IDC_RANDOM_CHECK  109
#define IDC_PUBLIC_KEY_BOX 110
#define IDC_SAVE_SIGNATURE 111
#define IDC_SETTINGS_BUTTON 112
#define IDC_ACTIVE_USER   113

#define IDC_MENU_ACTIVE_USER 150
#define IDC_MENU_CREATE_USER 151
#define IDC_MENU_SELECT_USER 152
#define IDC_MENU_KEY_WINDOW 153
#define IDC_MENU_OPEN_SIGN 154

#define IDC_CREATE_USER_NAME 170
#define IDC_CREATE_USER_SAVE 171
#define IDC_CREATE_USER_LIST 172
#define IDC_CREATE_USER_STATUS 173

#define IDC_SELECT_USER_LIST 180
#define IDC_SELECT_USER_APPLY 181
#define IDC_SELECT_USER_STATUS 182

#define IDC_KEY_PRIVATE 190
#define IDC_KEY_PUBLIC 191
#define IDC_KEY_GENERATE 192
#define IDC_KEY_SAVE 193
#define IDC_KEY_STATUS 194
#define IDI_APP_ICON 201
