#pragma once

#define IDC_FILEPATH_EDIT 101
#define IDC_BROWSE_BUTTON 102
#define IDC_SIGN_BUTTON   103
#define IDC_SIGNATURE_BOX 104
#define IDC_PRIVATE_KEY   105
#define IDC_PARAM_SET     106
#define IDC_HASH_COMBO    107
#define IDC_STATUS_TEXT   108
#define IDC_RANDOM_CHECK  109
#define IDC_PUBLIC_KEY_BOX 110
#define IDC_SAVE_SIGNATURE 111
#define IDC_SETTINGS_BUTTON 112
#define IDI_APP_ICON 201
